server:
  port: 5000

spring:
  cloud:
    gateway:
      routes:
        - id: oss
          uri: lb://xiong-club-oss
          predicates:
            - Path=/oss/**
          filters:
            - StripPrefix=1
        - id: auth
          uri: lb://xiong-club-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: subject
          uri: lb://xiong-club-subject
          predicates:
            - Path=/subject/**
          filters:
            - StripPrefix=1